function inputs = physical_inputs(e, r, hx_theta, fan, fpr_init, ...
    M_dot_coolant, n_modules, Q_tot, T_in_fc, T_out_fc, h, p11, t11, ...
    d2_init, AR_diff, AR_noz, V_inf, R, flight_phase, M_dot_FOD, M_dot_comp, ...
    solve_T, tol_T)
%PHYSICAL_INPUTS  "Physical input configuration" struct used as the
%results_index.mat matching key for both run_disc_model_fwdpass and
%run_lumped_model -- every physical input EXCEPT the discretised model's
%selector trio (N_segments, N_cool_seg, use_DNS), plus solve_T.
%
% tol_T is optional (omit it, or pass []): the discretised model has a
% length-solving tolerance and should pass it; the lumped model has no
% such loop and should leave it out. Passing or skipping it is the only
% difference between a lumped-model key and a discretised-model key --
% everything else is identical, so one function serves both callers
% rather than two near-duplicate ones.
%
% Shared between run_disc_model_fwdpass/run_lumped_model (when they save)
% and any calling script doing a cache lookup with find_matching_id
% BEFORE calling either of them, so the key is never built differently in
% two places. Call this with exactly the same argument values you are
% about to pass into (or just passed into) the model function.

if nargin < 23 || isempty(tol_T)
    inputs = struct( ...
        'e', e, 'r', r, 'hx_theta', hx_theta, 'fan', fan, 'fpr_init', fpr_init, ...
        'M_dot_coolant', M_dot_coolant, 'n_modules', n_modules, 'Q_tot', Q_tot, ...
        'T_in_fc', T_in_fc, 'T_out_fc', T_out_fc, 'h', h, 'p11', p11, 't11', t11, ...
        'd2_init', d2_init, 'AR_diff', AR_diff, 'AR_noz', AR_noz, 'V_inf', V_inf, ...
        'R', R, 'flight_phase', flight_phase, 'M_dot_FOD', M_dot_FOD, ...
        'M_dot_comp', M_dot_comp, 'solve_T', solve_T);
else
    inputs = struct( ...
        'e', e, 'r', r, 'hx_theta', hx_theta, 'fan', fan, 'fpr_init', fpr_init, ...
        'M_dot_coolant', M_dot_coolant, 'n_modules', n_modules, 'Q_tot', Q_tot, ...
        'T_in_fc', T_in_fc, 'T_out_fc', T_out_fc, 'h', h, 'p11', p11, 't11', t11, ...
        'd2_init', d2_init, 'AR_diff', AR_diff, 'AR_noz', AR_noz, 'V_inf', V_inf, ...
        'R', R, 'flight_phase', flight_phase, 'M_dot_FOD', M_dot_FOD, ...
        'M_dot_comp', M_dot_comp, 'solve_T', solve_T, 'tol_T', tol_T);
end

end